### ISSUE TITLE
[BUG] `linsolve` on GPU crashes

### ISSUE THREAD

**Issue by hjkqubit** [ITensor/ITensorTDVP.jl#51] opened 2023-02-02 21:54 UTC
**Description of bug**

Using the GPU on `test_linsolve.jl` code crashes even though it works on the CPU.

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors
using ITensorTDVP
using ITensorGPU
using CUDA
using Random

let
    gpu = cu

    cutoff = 1E-11
    maxdim = 8
    nsweeps = 2

    N = 8
    s = siteinds("S=1/2", N)

    os = OpSum()
    for j in 1:(N - 1)
      os += 0.5, "S+", j, "S-", j + 1
      os += 0.5, "S-", j, "S+", j + 1
      os += "Sz", j, "Sz", j + 1
    end
    H = MPO(os, s)

    ## Correct x is x_c
    x_c = randomMPS(s; linkdims=4)
    # Compute b
    b = apply(H, x_c; cutoff)

    x0 = randomMPS(s; linkdims=10)
    x = linsolve(H, b, x0; cutoff, maxdim, nsweeps, ishermitian=true, solver_tol=1E-6)

    @show norm(x - x_c)

    H = gpu(H)
    x_c = gpu(x_c)
    b = gpu(b)
    x0 = gpu(x0)

    x = linsolve(H, b, x0; cutoff, maxdim, nsweeps, ishermitian=true, solver_tol=1E-6)
    @show norm(x - x_c)
end
```
</p></details>

**Expected output or behavior**

We would expect similar `norm(x-x_c)` values for both the GPU and CPU versions.

**Actual output or behavior**

While the CPU code runs, the GPU code crashes with `StackOverflowError`. Line 40 is when linsolve is called after the `MPO`s were placed in the GPU.

<details><summary>Output of minimal runnable code</summary><p>

```julia
julia> include("test_linsolve_gpu.jl")
norm(x - x_c) = 2.0657141003163934e-7
ERROR: LoadError: StackOverflowError:
Stacktrace:
  [1] similar(::Type{SimpleTraits.Not{NDTensors.IsWrappedArray{DataType}}}, ::Type, ::Type, ::Type, ::Vararg{Any}) (repeats 16909 times)
    @ NDTensors C:\Users\hjkqu\.julia\packages\SimpleTraits\l1ZsK\src\SimpleTraits.jl:331
  [2] similar(D::NDTensors.Dense{Float64, CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}})
    @ NDTensors C:\Users\hjkqu\.julia\packages\NDTensors\FHyfI\src\dense\dense.jl:75
  [3] similar(T::NDTensors.DenseTensor{Float64, 3, Tuple{Index{Int64}, Index{Int64}, Index{Int64}}, NDTensors.Dense{Float64, CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}})
    @ NDTensors C:\Users\hjkqu\.julia\packages\NDTensors\FHyfI\src\tensor.jl:174
  [4] similar(::ITensor)
    @ ITensors C:\Users\hjkqu\.julia\packages\ITensors\AXb8G\src\itensor.jl:1699
  [5] linsolve(operator::ITensorTDVP.ProjMPO_MPS2, b::ITensor, x₀::ITensor, alg::KrylovKit.GMRES{KrylovKit.ModifiedGramSchmidt2, Float64}, a₀::Int64, a₁::Int64)
    @ KrylovKit C:\Users\hjkqu\.julia\packages\KrylovKit\diNbc\src\linsolve\gmres.jl:11
  [6] #linsolve#79
    @ C:\Users\hjkqu\.julia\packages\KrylovKit\diNbc\src\linsolve\linsolve.jl:101 [inlined]
  [7] (::ITensorTDVP.var"#linsolve_solver#68"{ITensorTDVP.var"#linsolve_solver#67#69"{Int64, Int64}})(P::ITensorTDVP.ProjMPO_MPS2, t::Float64, x₀::ITensor; ishermitian::Bool, solver_tol::Float64, solver_krylovdim::Int64, solver_maxiter::Int64, solver_verbosity::Int64, kwargs::Base.Pairs{Symbol, Real, Tuple{Symbol, Symbol}, NamedTuple{(:current_time, :outputlevel), Tuple{Float64, Int64}}})
    @ ITensorTDVP C:\Users\hjkqu\.julia\packages\ITensorTDVP\u9Bwz\src\linsolve.jl:41
  [8] tdvp_site_update!(nsite_val::Val{2}, reverse_step_val::Val{false}, solver::ITensorTDVP.var"#linsolve_solver#68"{ITensorTDVP.var"#linsolve_solver#67#69"{Int64, Int64}}, PH::ITensorTDVP.ProjMPO_MPS2, psi::MPS, b::Int64; current_time::Float64, outputlevel::Int64, time_step::Float64, normalize::Bool, direction::Base.Order.ForwardOrdering, noise::Float64, which_decomp::Nothing, svd_alg::String, cutoff::Float64, maxdim::Int64, mindim::Int64, maxtruncerr::Float64)
    @ ITensorTDVP C:\Users\hjkqu\.julia\packages\ITensorTDVP\u9Bwz\src\tdvp_step.jl:304
  [9] tdvp_site_update!(solver::ITensorTDVP.var"#linsolve_solver#68"{ITensorTDVP.var"#linsolve_solver#67#69"{Int64, Int64}}, PH::ITensorTDVP.ProjMPO_MPS2, psi::MPS, b::Int64; nsite::Int64, reverse_step::Bool, current_time::Float64, outputlevel::Int64, time_step::Float64, normalize::Bool, direction::Base.Order.ForwardOrdering, noise::Float64, which_decomp::Nothing, svd_alg::String, cutoff::Float64, maxdim::Int64, mindim::Int64, maxtruncerr::Float64)
    @ ITensorTDVP C:\Users\hjkqu\.julia\packages\ITensorTDVP\u9Bwz\src\tdvp_step.jl:157
 [10] tdvp_sweep(direction::Base.Order.ForwardOrdering, solver::Function, PH::ITensorTDVP.ProjMPO_MPS2, time_step::Float64, psi::MPS; kwargs::Base.Pairs{Symbol, Real, NTuple{10, Symbol}, NamedTuple{(:current_time, :reverse_step, :cutoff, :maxdim, :nsweeps, :ishermitian, :solver_tol, :sweep, :mindim, :noise), Tuple{Float64, Bool, Float64, Int64, Int64, Bool, Float64, Int64, Int64, Float64}}})        
    @ ITensorTDVP C:\Users\hjkqu\.julia\packages\ITensorTDVP\u9Bwz\src\tdvp_step.jl:80
 [11] tdvp_step(order::ITensorTDVP.TDVPOrder{2, Base.Order.ForwardOrdering()}, solver::Function, PH::ITensorTDVP.ProjMPO_MPS2, time_step::Float64, psi::MPS; current_time::Float64, kwargs::Base.Pairs{Symbol, Real, NTuple{9, Symbol}, NamedTuple{(:reverse_step, :cutoff, :maxdim, :nsweeps, :ishermitian, :solver_tol, :sweep, :mindim, :noise), Tuple{Bool, Float64, Int64, Int64, Bool, Float64, Int64, Int64, Float64}}})
    @ ITensorTDVP C:\Users\hjkqu\.julia\packages\ITensorTDVP\u9Bwz\src\tdvp_step.jl:9
 [12] macro expansion
    @ C:\Users\hjkqu\.julia\packages\ITensorTDVP\u9Bwz\src\tdvp_generic.jl:84 [inlined]
 [13] macro expansion
    @ .\timing.jl:299 [inlined]
 [14] tdvp(solver::Function, PH::ITensorTDVP.ProjMPO_MPS2, t::Float64, psi0::MPS; kwargs::Base.Pairs{Symbol, Real, NTuple{6, Symbol}, NamedTuple{(:reverse_step, :cutoff, :maxdim, :nsweeps, :ishermitian, :solver_tol), Tuple{Bool, Float64, Int64, Int64, Bool, Float64}}})
    @ ITensorTDVP C:\Users\hjkqu\.julia\packages\ITensorTDVP\u9Bwz\src\tdvp_generic.jl:83
 [15] linsolve(A::MPO, b::MPS, x₀::MPS, a₀::Int64, a₁::Int64; kwargs::Base.Pairs{Symbol, Real, NTuple{5, Symbol}, NamedTuple{(:cutoff, :maxdim, :nsweeps, :ishermitian, :solver_tol), Tuple{Float64, Int64, Int64, Bool, Float64}}})
    @ ITensorTDVP C:\Users\hjkqu\.julia\packages\ITensorTDVP\u9Bwz\src\linsolve.jl:47
 [16] top-level scope
    @ C:\Users\hjkqu\Documents\Code\AGP-MPO\test_linsolve_gpu.jl:40
 [17] include(fname::String)
    @ Base.MainInclude .\client.jl:451
in expression starting at C:\Users\hjkqu\Documents\Code\AGP-MPO\test_linsolve_gpu.jl:7
```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 9 4900HS with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
[9136182c] ITensors v0.3.24
```
 - Output from `using Pkg; Pkg.status("ITensorTDVP")`:
```julia
julia> using Pkg; Pkg.status("ITensorTDVP")
[25707e16] ITensorTDVP v0.0.4
```

**Comment by mtfishman** [comment] 2023-02-02 22:16
@kmp5VT probably this is fixed by https://github.com/ITensor/ITensors.jl/pull/1040? It looks like `similar(T::ITensor)` is broken for `datatype(T) isa CuArray`.

**Comment by mtfishman** [comment] 2023-02-03 17:58
Should get fixed by https://github.com/ITensor/ITensors.jl/pull/1051. A more minimal example to reproduce this error is:
```julia
using ITensors
using CUDA
using ITensorGPU

similar(itensor(CuArray(randn(2)), Index(2)))
```

**Closed** 2023-02-07 19:01 UTC
